version: '2'
services:
  node01:
    image: percona/percona-server
    container_name: ${COMPOSE_PROJECT_NAME}_node01
    networks:
      mha_network:
        ipv4_address: ${NODE_1_IP_ADDRESS}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./.ssh/:/root/.ssh/
      - ./my.cnf.node01:/etc/mysql/my.cnf
    extra_hosts:
      - "node02:${NODE_2_IP_ADDRESS}"
      - "node03:${NODE_3_IP_ADDRESS}"

  node02:
    image: percona/percona-server
    container_name: ${COMPOSE_PROJECT_NAME}_node02
    networks:
      mha_network:
        ipv4_address: ${NODE_2_IP_ADDRESS}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./.ssh/:/root/.ssh/
      - ./my.cnf.node02:/etc/mysql/my.cnf
    extra_hosts:
      - "node01:${NODE_1_IP_ADDRESS}"
      - "node03:${NODE_3_IP_ADDRESS}"
    depends_on:
      - node01

  node03:
    image: percona/percona-server
    container_name: ${COMPOSE_PROJECT_NAME}_node03
    networks:
      mha_network:
        ipv4_address: ${NODE_3_IP_ADDRESS}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./.ssh/:/root/.ssh/
      - ./my.cnf.node03:/etc/mysql/my.cnf
    extra_hosts:
      - "node01:${NODE_1_IP_ADDRESS}"
      - "node02:${NODE_2_IP_ADDRESS}"
    depends_on:
      - node02

  manager:
    image: percona/percona-server
    container_name: ${COMPOSE_PROJECT_NAME}_manager
    networks:
      mha_network:
        ipv4_address: ${MANAGER_NODE_IP_ADDRESS}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./.ssh/:/root/.ssh/
      - ./manager.cnf:/etc/manager.cnf
    extra_hosts:
      - "node01:${NODE_1_IP_ADDRESS}"
      - "node02:${NODE_2_IP_ADDRESS}"
      - "node03:${NODE_3_IP_ADDRESS}"
    depends_on:
      - node03

networks:
  mha_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}
          gateway: ${NETWORK_GATEWAY}

