version: '3.5'
services:
  orchestrator01:
    image: ${ORCHESTRATOR_IMAGE}:${ORCHESTRATOR_TAG}
    container_name: orchestrator_${COMPOSE_PROJECT_NAME}_orchestrator_1
    hostname: orchestrator_${COMPOSE_PROJECT_NAME}_orchestrator_1
    networks:
      orch_network:
    ports:
      - 3000
    volumes:
      - ./cnf_files/orchestrator_1.cnf:/etc/orchestrator.conf.json

  orchestrator02:
    image: ${ORCHESTRATOR_IMAGE}:${ORCHESTRATOR_TAG}
    container_name: orchestrator_${COMPOSE_PROJECT_NAME}_orchestrator_2
    hostname: orchestrator_${COMPOSE_PROJECT_NAME}_orchestrator_2
    networks:
      orch_network:
    ports:
      - 3000
    depends_on:
      - orchestrator01
    volumes:
      - ./cnf_files/orchestrator_2.cnf:/etc/orchestrator.conf.json

  orchestrator03:
    image: ${ORCHESTRATOR_IMAGE}:${ORCHESTRATOR_TAG}
    container_name: orchestrator_${COMPOSE_PROJECT_NAME}_orchestrator_3
    hostname: orchestrator_${COMPOSE_PROJECT_NAME}_orchestrator_3
    networks:
      orch_network:
    ports:
      - 3000
    depends_on:
      - orchestrator02
    volumes:
      - ./cnf_files/orchestrator_3.cnf:/etc/orchestrator.conf.json

networks:
  orch_network:
    name: ${NETWORK_NAME}
    driver: bridge

