version: '2'
services:
  node01:
    image: percona/percona-server
    container_name: ${COMPOSE_PROJECT_NAME}_mha_node01
    networks:
      mha_network:
        ipv4_address: ${NODE_1_IP_ADDRESS}
    environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  nodeN:
    image: percona/percona-server
    networks:
      - mha_network
    environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - node01

networks:
  mha_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}
          gateway: ${NETWORK_GATEWAY}

