version: '2'
services:
  cluster01_node01:
    image: ${IMAGE}:${TAG}
    container_name: ${COMPOSE_PROJECT_NAME}_pxc_cluster01_node01
    networks:
      - pxc_network
    environment:
            CLUSTER_NAME: ${CLUSTER_NAME}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            XTRABACKUP_PASSWORD: ${XTRABACKUP_PASSWORD}
            CLUSTER_JOIN:

  cluster01_nodeN:
    image: ${IMAGE}:${TAG}
    networks:
      - pxc_network
    environment:
            CLUSTER_NAME: ${CLUSTER_NAME}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            XTRABACKUP_PASSWORD: ${XTRABACKUP_PASSWORD}
            CLUSTER_JOIN: ${COMPOSE_PROJECT_NAME}_pxc_cluster01_node01
    depends_on:
      - cluster01_node01

  cluster02_node01:
    image: ${IMAGE}:${TAG}
    container_name: ${COMPOSE_PROJECT_NAME}_pxc_cluster02_node01
    networks:
      - pxc_network
    environment:
            CLUSTER_NAME: ${CLUSTER_NAME}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            XTRABACKUP_PASSWORD: ${XTRABACKUP_PASSWORD}
            CLUSTER_JOIN:

  cluster02_nodeN:
    image: ${IMAGE}:${TAG}
    networks:
      - pxc_network
    environment:
            CLUSTER_NAME: ${CLUSTER_NAME}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            XTRABACKUP_PASSWORD: ${XTRABACKUP_PASSWORD}
            CLUSTER_JOIN: ${COMPOSE_PROJECT_NAME}_pxc_cluster02_node01
    depends_on:
      - cluster02_node01

networks:
  pxc_network:
    driver: bridge

